#=====================================================
# output
#=====================================================

# global stat
/gate/actor/addActor  SimulationStatisticActor stat
/gate/actor/stat/save output/stat.txt

# ROOT OUTPUT 
/gate/output/root/enable
/gate/output/root/setFileName 			output/pet

/gate/output/root/setRootCoincidencesFlag 	1
/gate/output/root/setRootdelayFlag 		1
/gate/output/root/setRootNtupleFlag 		0
/gate/output/root/setRootHitFlag 		0
/gate/output/root/setRootSinglesFlag 		1
/gate/output/root/setSaveRndmFlag 		0
/gate/output/root/setRootRecordFlag 		0



