#=====================================================
# output
#=====================================================

# global stat
/gate/actor/addActor  SimulationStatisticActor stat
/gate/actor/stat/save output/stat.txt

# ROOT OUTPUT 
/gate/output/root/enable                          # Enable ROOT output format
/gate/output/root/setFileName 			output/pet    # Set the base name for ROOT output files

# Configure what information is stored in the ROOT file
/gate/output/root/setRootCoincidencesFlag 	1
/gate/output/root/setRootdelayFlag 		1
/gate/output/root/setRootNtupleFlag 		0
/gate/output/root/setRootHitFlag 		0
/gate/output/root/setRootSinglesFlag 		0
/gate/output/root/setSaveRndmFlag 		0
/gate/output/root/setRootRecordFlag 		0



